### ISSUE TITLE
Web login required

### ISSUE THREAD

**Issue by Juby210** [Jarijaas/go-googleplay#1]
I don't seem to be able to use this library anymore, always returns error.

**Comment by Jarijaas** [comment]
Hey @Juby210,

I'm working on fixing this

**Comment by Jarijaas** [comment]
Check out the [v0.2.0](https://github.com/Jarijaas/go-googleplay/releases/tag/v0.2.0-dev2) release. The web login requires manual login using browser. The app launches chrome and retrieves the oauth2_token after the login is complete. This requires a `droidguard_rules` value, which is probably some kind of anti-bot mechanism. I hardcoded this currently so it probably changes at some point, so it wont work forever. I believe that this weblogin was caused by the default device profile. I added some new profiles and the profile can be changed using the `--profile` cli option.  The cli also supports cloning the device profile that is connected to the computer using adb.

**Comment by Juby210** [comment]
Thank you, for now I am not able to test it. I will test it in 3 days. Btw will it work on a server without a browser? I copied gsf and authsubtoken from my pc before to my server, so I guess I am still able to do that.

**Comment by Jarijaas** [comment]
Yeah, if you copy the tokens it should work normally

**Comment by Juby210** [comment]
Thank you, works fine now
